function res = repr(Op, n, m)
    %rest = cell(n, n);
    tmp = zeros(n, n);
    %for i = 1 : n
    %    for j = 1 : n
    %        tmp(i, j) = 1;
    %        rest{i, j} = Op(tmp);
    %        tmp(i, j) = 0;
    %    end
    %end
    
    function res2 = at_t(t)
        res2 = zeros(n, n, m, m);
        for i = 1 : n
            for j = 1 : n
                tmp(i, j) = 1;
                optmp = Op(tmp);
                res2(i, j, :, :) = optmp(t);
                tmp(i, j) = 0;
            end
        end
    end
    
    %res = convert_cellarray_to_matrix(rest, n, m);
    res = @at_t;
    
%     rest(0);
%     
%     ab = cellfun( ...
%                         @(f) f(0), ...
%                         rest, ...
%                         'UniformOutput', false ...
%                     )
%     cd = mat2cell(cellfun(@(a) num2cell(a), ab, 'UniformOutput', false))
%     celldisp(cd)
% % 
% %     
% %     cell2mat(ab)
% %     celldisp(ab)
% % 
% %     ab = num2cell( ...
% %             cellfun( ...
% %                 @cell2mat, ...
% %                 num2cell( ...
% %                     cellfun( ...
% %                         @(f) f(0), ...
% %                         rest, ...
% %                         'UniformOutput', false ...
% %                     ) ...
% %                 ), ...
% %                 'UniformOutput', false ...
% %         ))
% %     
% %     iscell(ab)
% %     celldisp(ab)
% %     
% %     cell2mat( ...
% %         num2cell( ...
% %             cellfun( ...
% %                 @cell2mat, ...
% %                 num2cell( ...
% %                     cellfun( ...
% %                         @(f) f(0), ...
% %                         rest, ...
% %                         'UniformOutput', false ...
% %                     ) ...
% %                 ), ...
% %                 'UniformOutput', false ...
% %         )))
% %     
%      res = @(t) cell2mat( ...
%              cellfun( ...
%                  @num2cell, ...
%                  cellfun( ...
%                     @(f) f(t), ...
%                     rest, ...
%                     'UniformOutput', false ...
%                  ), ...
%              'UniformOutput', false ...
%              ) ...
%          );
end
